### ISSUE TITLE
App won't launch

### ISSUE THREAD

**Issue by kudlav** [blockbasti/just_another_workout_timer#108]
**Describe the bug**
Unable to launch the app installed from f-droid

**To Reproduce**
1. Install the app from f-droid
2. Launch the app
3. The app shows splash screen and that's all

**Expected behavior**
App should launch.

**Screenshots**
![Screenshot_20220203-200124](https://user-images.githubusercontent.com/11516259/152410834-ce5dcb03-0a01-4f1e-818c-b9d32895dd69.png)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A40 (SM-A405FN)
 - OS:Android 11
 - Version 1.10.0

**Additional context**
Lang: cs-CZ

**Comment by neunenak** [comment]
I believe I'm seeing this same issue. I have a OnePlus 7Pro, running Lineage OS nightly (as of a few days ago), Android 11, with no google services.

**Comment by blockbasti** [comment]
Can you try the debug build from [here](https://github.com/blockbasti/just_another_workout_timer/actions/runs/1801993315)(it will install alongside the F-Droid version) and if you are able to, provide a logcat? Have you tried setting your device language to english?

I've tried the F-Droid version on my device, even changing the language to czech, but cannot reproduce the problem.

**Comment by daBaret** [comment]
Hi,
I have the same problem. Here you can see de debug log of my device.

Thank you :)

```
022-02-07 09:30:26.582 1079-5902/system_process I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.blockbasti.justanotherworkouttimer.debug/com.blockbasti.just_another_workout_timer.MainActivity bnds=[33,97][236,418]} from uid 10162
2022-02-07 09:30:26.599 1079-1106/system_process I/ActivityManager: Start proc 11861:com.blockbasti.justanotherworkouttimer.debug/u0a257 for pre-top-activity {com.blockbasti.justanotherworkouttimer.debug/com.blockbasti.just_another_workout_timer.MainActivity}
2022-02-07 09:30:26.666 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-02-07 09:30:26.667 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-02-07 09:30:26.697 11861-24062/com.blockbasti.justanotherworkouttimer.debug I/ResourceExtractor: Found extracted resources res_timestamp-20220206-1644216392771
2022-02-07 09:30:26.697 11861-11861/com.blockbasti.justanotherworkouttimer.debug W/kouttimer.debug: type=1400 audit(0.0:183633): avc: denied { read } for name="max_map_count" dev="proc" ino=20711467 scontext=u:r:untrusted_app:s0:c1,c257,c512,c768 tcontext=u:object_r:proc_max_map_count:s0 tclass=file permissive=0 app=com.blockbasti.justanotherworkouttimer.debug
2022-02-07 09:30:26.711 11861-11861/com.blockbasti.justanotherworkouttimer.debug I/AdrenoGLES-0: QUALCOMM build                   : 8e5405b, I57aaec3440
    Build Date                       : 05/21/21
    OpenGL ES Shader Compiler Version: EV031.32.02.10
    Local Branch                     : mybranchebba1dbe-451b-f160-ac81-1458d0b52ae8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r135-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2022-02-07 09:30:26.711 11861-11861/com.blockbasti.justanotherworkouttimer.debug I/AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
2022-02-07 09:30:26.711 11861-11861/com.blockbasti.justanotherworkouttimer.debug I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2022-02-07 09:30:26.714 11861-11861/com.blockbasti.justanotherworkouttimer.debug I/AdrenoGLES-0: PFP: 0x016ee19a, ME: 0x00000000
2022-02-07 09:30:26.725 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/FlutterFileDialogPlugin: onAttachedToEngine - IN
2022-02-07 09:30:26.725 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/FlutterFileDialogPlugin: doOnAttachedToEngine - IN
2022-02-07 09:30:26.725 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/FlutterFileDialogPlugin: doOnAttachedToEngine - OUT
2022-02-07 09:30:26.725 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/FlutterFileDialogPlugin: onAttachedToEngine - OUT
2022-02-07 09:30:26.725 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/FlutterFileDialogPlugin: onAttachedToActivity
2022-02-07 09:30:26.726 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/FlutterFileDialogPlugin: doOnAttachedToActivity - IN
2022-02-07 09:30:26.726 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/FlutterFileDialogPlugin: doOnAttachedToActivity - OUT
2022-02-07 09:30:26.733 11861-11861/com.blockbasti.justanotherworkouttimer.debug E/TTS: Failed to initialize TextToSpeech
2022-02-07 09:30:26.736 11861-11861/com.blockbasti.justanotherworkouttimer.debug D/PathProviderPlugin: Don't use TaskQueues.
2022-02-07 09:30:26.756 11861-11861/com.blockbasti.justanotherworkouttimer.debug W/kouttimer.debu: Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (greylist,test-api, reflection, allowed)
2022-02-07 09:30:26.756 11861-11861/com.blockbasti.justanotherworkouttimer.debug W/kouttimer.debu: Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (greylist, reflection, allowed)
2022-02-07 09:30:26.757 11861-11861/com.blockbasti.justanotherworkouttimer.debug W/kouttimer.debu: Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (greylist, reflection, allowed)
2022-02-07 09:30:26.757 11861-11861/com.blockbasti.justanotherworkouttimer.debug W/kouttimer.debu: Accessing hidden method Landroid/util/LongArray;->get(I)J (greylist, reflection, allowed)
2022-02-07 09:30:26.847 11861-24080/com.blockbasti.justanotherworkouttimer.debug I/flutter: Observatory listening on http://127.0.0.1:37489/cyLoRnG6wLM=/
2022-02-07 09:30:27.248 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodec: allocate(c2.android.raw.decoder)
2022-02-07 09:30:27.249 11861-24085/com.blockbasti.justanotherworkouttimer.debug I/Codec2Client: Available Codec2 services: "software"
2022-02-07 09:30:27.252 11861-24085/com.blockbasti.justanotherworkouttimer.debug I/CCodec: Created component [c2.android.raw.decoder]
2022-02-07 09:30:27.252 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: read media type: audio/raw
2022-02-07 09:30:27.253 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
2022-02-07 09:30:27.253 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
2022-02-07 09:30:27.253 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
2022-02-07 09:30:27.254 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
2022-02-07 09:30:27.254 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
2022-02-07 09:30:27.254 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
2022-02-07 09:30:27.254 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
2022-02-07 09:30:27.254 11861-24085/com.blockbasti.justanotherworkouttimer.debug I/CCodecConfig: query failed after returning 8 values (BAD_INDEX)
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: c2 config diff is Dict {
      c2::u32 coded.bitrate.value = 64000
      c2::u32 input.buffers.max-size.value = 65536
      c2::u32 input.delay.value = 0
      string input.media-type.value = "audio/raw"
      string output.media-type.value = "audio/raw"
      c2::u32 raw.channel-count.value = 2
      c2::u32 raw.pcm-encoding.value = 0
      c2::u32 raw.sample-rate.value = 44100
    }
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodec: [c2.android.raw.decoder] buffers are bound to CCodec for this session
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for durationUs
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for track-id
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for bits-per-sample
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for channel-mask
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for flags
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: c2 config diff is   c2::u32 raw.channel-count.value = 1
      c2::u32 raw.sample-rate.value = 8000
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 1107298332.
2022-02-07 09:30:27.255 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodec: setup formats input: AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      int32_t max-input-size = 65536
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
    } and output: AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
      int32_t channel-mask = 0
    }
2022-02-07 09:30:27.256 11861-24085/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 1342179345.
2022-02-07 09:30:27.256 11861-24085/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 2415921170.
2022-02-07 09:30:27.256 11861-24085/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.256 11861-24085/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.256 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#67] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
2022-02-07 09:30:27.257 11861-24085/com.blockbasti.justanotherworkouttimer.debug I/CCodecBufferChannel: [c2.android.raw.decoder#67] Created output block pool with allocatorID 16 => poolID 891 - OK
2022-02-07 09:30:27.257 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#67] Configured output block pool ids 891 => OK
2022-02-07 09:30:27.257 11861-24085/com.blockbasti.justanotherworkouttimer.debug E/ion: ioctl c0044901 failed with code -1: Invalid argument
2022-02-07 09:30:27.259 11861-24085/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.260 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecBuffers: [c2.android.raw.decoder#67:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
      int32_t channel-mask = 0
    }
2022-02-07 09:30:27.260 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#67] MediaCodec discarded an unknown buffer
2022-02-07 09:30:27.260 11861-24085/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#67] MediaCodec discarded an unknown buffer
2022-02-07 09:30:27.261 11861-24085/com.blockbasti.justanotherworkouttimer.debug I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2022-02-07 09:30:27.314 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodec: allocate(c2.android.raw.decoder)
2022-02-07 09:30:27.315 11861-24094/com.blockbasti.justanotherworkouttimer.debug I/CCodec: Created component [c2.android.raw.decoder]
2022-02-07 09:30:27.316 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: read media type: audio/raw
2022-02-07 09:30:27.317 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
2022-02-07 09:30:27.317 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
2022-02-07 09:30:27.317 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
2022-02-07 09:30:27.317 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
2022-02-07 09:30:27.317 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
2022-02-07 09:30:27.317 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
2022-02-07 09:30:27.317 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug I/CCodecConfig: query failed after returning 8 values (BAD_INDEX)
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: c2 config diff is Dict {
      c2::u32 coded.bitrate.value = 64000
      c2::u32 input.buffers.max-size.value = 65536
      c2::u32 input.delay.value = 0
      string input.media-type.value = "audio/raw"
      string output.media-type.value = "audio/raw"
      c2::u32 raw.channel-count.value = 2
      c2::u32 raw.pcm-encoding.value = 0
      c2::u32 raw.sample-rate.value = 44100
    }
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodec: [c2.android.raw.decoder] buffers are bound to CCodec for this session
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for durationUs
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for track-id
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for bits-per-sample
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for channel-mask
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for flags
2022-02-07 09:30:27.318 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: c2 config diff is   c2::u32 raw.channel-count.value = 1
      c2::u32 raw.sample-rate.value = 8000
2022-02-07 09:30:27.319 11861-24094/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 1107298332.
2022-02-07 09:30:27.319 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodec: setup formats input: AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      int32_t max-input-size = 65536
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
    } and output: AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
      int32_t channel-mask = 0
    }
2022-02-07 09:30:27.319 11861-24094/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 1342179345.
2022-02-07 09:30:27.319 11861-24094/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 2415921170.
2022-02-07 09:30:27.319 11861-24094/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.319 11861-24094/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.319 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#875] Created input block pool with allocatorID 16 => poolID 18 - OK (0)
2022-02-07 09:30:27.320 11861-24094/com.blockbasti.justanotherworkouttimer.debug I/CCodecBufferChannel: [c2.android.raw.decoder#875] Created output block pool with allocatorID 16 => poolID 892 - OK
2022-02-07 09:30:27.320 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#875] Configured output block pool ids 892 => OK
2022-02-07 09:30:27.321 11861-24094/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.322 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecBuffers: [c2.android.raw.decoder#875:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
      int32_t channel-mask = 0
    }
2022-02-07 09:30:27.323 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#875] MediaCodec discarded an unknown buffer
2022-02-07 09:30:27.323 11861-24094/com.blockbasti.justanotherworkouttimer.debug I/chatty: uid=10257(com.blockbasti.justanotherworkouttimer.debug) identical 1 line
2022-02-07 09:30:27.323 11861-24094/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#875] MediaCodec discarded an unknown buffer
2022-02-07 09:30:27.323 11861-24094/com.blockbasti.justanotherworkouttimer.debug I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2022-02-07 09:30:27.363 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodec: allocate(c2.android.raw.decoder)
2022-02-07 09:30:27.364 11861-24097/com.blockbasti.justanotherworkouttimer.debug I/CCodec: Created component [c2.android.raw.decoder]
2022-02-07 09:30:27.365 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: read media type: audio/raw
2022-02-07 09:30:27.366 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.max-count.values
2022-02-07 09:30:27.366 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.subscribed-indices.values
2022-02-07 09:30:27.366 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: input.buffers.allocator-ids.values
2022-02-07 09:30:27.366 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.allocator-ids.values
2022-02-07 09:30:27.366 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.allocator-ids.values
2022-02-07 09:30:27.366 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: output.buffers.pool-ids.values
2022-02-07 09:30:27.366 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/ReflectedParamUpdater: extent() != 1 for single value type: algo.buffers.pool-ids.values
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug I/CCodecConfig: query failed after returning 8 values (BAD_INDEX)
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: c2 config diff is Dict {
      c2::u32 coded.bitrate.value = 64000
      c2::u32 input.buffers.max-size.value = 65536
      c2::u32 input.delay.value = 0
      string input.media-type.value = "audio/raw"
      string output.media-type.value = "audio/raw"
      c2::u32 raw.channel-count.value = 2
      c2::u32 raw.pcm-encoding.value = 0
      c2::u32 raw.sample-rate.value = 44100
    }
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodec: [c2.android.raw.decoder] buffers are bound to CCodec for this session
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for durationUs
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for track-id
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for bits-per-sample
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for channel-mask
2022-02-07 09:30:27.367 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: no c2 equivalents for flags
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecConfig: c2 config diff is   c2::u32 raw.channel-count.value = 1
      c2::u32 raw.sample-rate.value = 8000
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 1107298332.
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodec: setup formats input: AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      int32_t max-input-size = 65536
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
    } and output: AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
      int32_t channel-mask = 0
    }
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 1342179345.
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug W/Codec2Client: query -- param skipped: index = 2415921170.
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.368 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#532] Created input block pool with allocatorID 16 => poolID 19 - OK (0)
2022-02-07 09:30:27.369 11861-24097/com.blockbasti.justanotherworkouttimer.debug I/CCodecBufferChannel: [c2.android.raw.decoder#532] Created output block pool with allocatorID 16 => poolID 893 - OK
2022-02-07 09:30:27.369 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#532] Configured output block pool ids 893 => OK
2022-02-07 09:30:27.371 11861-24097/com.blockbasti.justanotherworkouttimer.debug E/FMQ: grantorIdx must be less than 3
2022-02-07 09:30:27.371 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecBuffers: [c2.android.raw.decoder#532:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
      int32_t channel-count = 1
      string mime = "audio/raw"
      int32_t pcm-encoding = 2
      int32_t sample-rate = 8000
      int32_t channel-mask = 0
    }
2022-02-07 09:30:27.372 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#532] MediaCodec discarded an unknown buffer
2022-02-07 09:30:27.372 11861-24097/com.blockbasti.justanotherworkouttimer.debug I/chatty: uid=10257(com.blockbasti.justanotherworkouttimer.debug) identical 1 line
2022-02-07 09:30:27.372 11861-24097/com.blockbasti.justanotherworkouttimer.debug D/CCodecBufferChannel: [c2.android.raw.decoder#532] MediaCodec discarded an unknown buffer
2022-02-07 09:30:27.373 11861-24097/com.blockbasti.justanotherworkouttimer.debug I/hw-BpHwBinder: onLastStrongRef automatically unlinking death recipients
2022-02-07 09:30:32.272 11861-24088/com.blockbasti.justanotherworkouttimer.debug D/BufferPoolAccessor2.0: bufferpool2 0x72e33ef6b8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 1/2 (fetch/transfer)
2022-02-07 09:30:32.272 11861-24088/com.blockbasti.justanotherworkouttimer.debug D/BufferPoolAccessor2.0: evictor expired: 1, evicted: 1
2022-02-07 09:30:33.300 11861-24088/com.blockbasti.justanotherworkouttimer.debug D/BufferPoolAccessor2.0: bufferpool2 0x72e33edf98 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 1/2 (fetch/transfer)
2022-02-07 09:30:33.300 11861-24088/com.blockbasti.justanotherworkouttimer.debug D/BufferPoolAccessor2.0: bufferpool2 0x72e33f14c8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 1/2 (fetch/transfer)
2022-02-07 09:30:33.300 11861-24088/com.blockbasti.justanotherworkouttimer.debug D/BufferPoolAccessor2.0: evictor expired: 2, evicted: 2

```

**Comment by kudlav** [comment]
Still not working in v1.11.0

**Comment by kudlav** [comment]
Setting the language to the English doesn't solve the problem.

**Comment by byronigoe** [comment]
1.10 works for me, but after updating to 1.11 it hangs at the splash screen. I uninstalled, then reinstalled 1.10, which still works.

**Comment by kudlav** [comment]
Hi, I've installed [this APK](https://github.com/blockbasti/just_another_workout_timer/actions/runs/1801993315).

Here's the logcat:
```
2022-02-15 09:45:20.110 15638-16213/com.blockbasti.justanotherworkouttimer.debug E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
    #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
    #1      TTSHelper.init (package:just_another_workout_timer/tts_helper.dart:53:25)
    <asynchronous suspension>
    #2      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
    <asynchronous suspension>
```
